config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views import defaults as default_views

from tigerleaflet.views import CountryView
from tigerleaflet.views import StateView
from tigerleaflet.views import CountyView

app_name = 'geodjango_tigerleaflet_example'
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),

    url(r'tigerleaflet/$',
        CountryView.as_view(template_name='pages/country.html'),
        name='country'),
    url(r'tigerleaflet/(?P<state>[a-z_]+)$',
        StateView.as_view(template_name='pages/state.html'),
        name='state'),
    url(r'tigerleaflet/(?P<state>[a-z_]+)/(?P<county>[a-z_]+)$',
        CountyView.as_view(template_name='pages/county.html'),
        name='county'),
    url(r'^tigerleaflet/', include('tigerleaflet.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}
           ),
        url(r'^403/$',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}
           ),
        url(r'^404/$',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}
           ),
        url(r'^500/$',
            default_views.server_error
           ),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

tigerleaflet/urls.py
from django.conf.urls import url

from .views import CountryData
from .views import StateData
from .views import CountyData

app_name = 'tigerleaflet'
urlpatterns = [
    # geojson urls
    url(r'^country.geojson$',
        CountryData.as_view(),
        name='country_data'),
    url(r'^state.geojson$',
        StateData.as_view(),
        name='state_data'),
    url(r'^county.geojson$',
        CountyData.as_view(),
        name='county_data'),
]

tigerleaflet/models.py
from django.contrib.gis.db import models


class State(models.Model):
    fips_code = models.CharField('FIPS Code', max_length=2)
    usps_code = models.CharField('USPS state abbreviation', max_length=2, db_index=True)
    name = models.CharField(max_length=100, db_index=True)
    area_description_code = models.CharField(max_length=2)
    feature_class_code = models.CharField(max_length=5)
    functional_status = models.CharField(max_length=1)
    mpoly = models.MultiPolygonField()

    objects = models.GeoManager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class County(models.Model):
    state = models.ForeignKey(State)
    # redundant field, but necessary until serializer overrides can be done
    usps_code = models.CharField('USPS state abbreviation', max_length=2)
    state_fips_code = models.CharField('State FIPS Code', max_length=2)
    fips_code = models.CharField('FIPS Code', max_length=3)
    county_identifier = models.CharField(max_length=5)
    name = models.CharField(max_length=100)
    name_and_description = models.CharField(max_length=100)
    legal_statistical_description = models.CharField(max_length=2)
    fips_55_class_code = models.CharField(max_length=2)
    feature_class_code = models.CharField(max_length=5)
    functional_status = models.CharField(max_length=1)
    mpoly = models.MultiPolygonField()

    objects = models.GeoManager()

    def save(self, *args, **kwargs):
        self.state = State.objects.get(fips_code=self.state_fips_code)
        self.usps_code = self.state.usps_code
        super(County, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Counties'

    def __str__(self):
        return self.name + ", " + self.usps_code

tigerleaflet/views.py
from django.core.serializers import serialize
from django.http import HttpResponse
from django.views.generic import View
from django.views.generic import TemplateView

from tigerleaflet.models import State
from tigerleaflet.models import County

def get_geojson(data, fields):
    return serialize('geojson', data, geometry_field='mpoly', fields=fields)


class CountryView(TemplateView):
    template_name = "countryview_default.html"

    def get_context_data(self, **kwargs):
        return { 'title': "US States"}


class CountryData(View):
    fields = ('name', 'usps_code', 'fips_code')

    def post(self, request):
        map_data = State.objects.raw(
            'SELECT id, ST_simplify(mpoly, 0.1) AS mpoly,'
            ' name, usps_code, fips_code'
            ' FROM tigerleaflet_state')
        geojson = get_geojson(map_data, self.fields)

        return HttpResponse(geojson, content_type='application/json')


class StateView(TemplateView):
    template_name = "stateview_default.html"

    def get_context_data(self, **kwargs):
        state_code = self.kwargs['state']
        state_name = State.objects.get(usps_code=state_code.upper()).name
        context = { 'title': "Showing " + state_name,
                    'state': state_code
                    }
        return context


class StateData(View):
    fields = ('name', 'usps_code', 'fips_code')

    def post(self, request):
        usps_code = self.request.POST['state'].upper()
        map_data = County.objects.raw(
            'SELECT id, ST_simplify(mpoly, 0.01) AS mpoly,'
            ' name, fips_code, usps_code FROM tigerleaflet_county'
            ' WHERE usps_code=%s', [usps_code],
        )
        geojson = get_geojson(map_data, self.fields)

        return HttpResponse(geojson, content_type='application/json')


class CountyView(TemplateView):
    template_name = "countyview_default.html"

    def get_context_data(self, **kwargs):
        state_code = self.kwargs['state']
        county = self.kwargs['county']
        state_name = State.objects.get(usps_code=state_code.upper()).name
        county_name = county.replace('_', ' ').title()
        context = { 'title' : county_name + ", " + state_name,
                    'state' : state_code,
                    'county': county,
                    }
        return context


class CountyData(View):
    fields = ('name', 'fips_code', 'usps_code')

    def post(self, request):
        usps_code = self.request.POST['state'].upper()
        county_name = self.request.POST['county'].replace("_", " ").title()
        map_data = County.objects.raw(
            'SELECT id, mpoly,'
            ' name, usps_code FROM tigerleaflet_county'
            ' WHERE usps_code=%s AND name=%s',
            [usps_code, county_name],
        )
        geojson = get_geojson(map_data, self.fields)

        return HttpResponse(geojson, content_type='application/json')

geodjango_tigerleaflet_example/templates/403_csrf.html
{% extends "app_base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

geodjango_tigerleaflet_example/templates/app_base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}geodjango-tigerleaflet-example{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    {% block extra_header %}{% endblock %}
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">geodjango-tigerleaflet-example</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'country' %}">Map Demo</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">
      {% block content %}
	      <p><a href="{% url 'country' %}">Go to Map Demo</a></p>
      {% endblock content %}
    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    {% block javascript %}
      {% block extra_javascript %}{% endblock %}
    {% endblock javascript %}
  </body>
</html>

geodjango_tigerleaflet_example/templates/pages/country.html
{% extends "app_base.html" %}

{% load tigerleaflet_tags %}

{% block title %}{{ title }}{% endblock title %}

{% block extra_header %}
  {% init_tigerleaflet_map %}
{% endblock extra_header %}

{% block content %}
  {% show_tigerleaflet_country 'tigerleaflet_map' "/tigerleaflet/" 37.22 -90.41 3 %}

  <script>
    L.marker([37, -90]).addTo(tigerleaflet_map)
    .bindPopup('An example of extending a tigerleaflet map.')
    .openPopup();
  </script>

{% endblock %}

geodjango_tigerleaflet_example/templates/pages/county.html
{% extends "app_base.html" %}

{% load tigerleaflet_tags %}

{% block title %}{{ title }}{% endblock title %}

{% block extra_header %}
  {% init_tigerleaflet_map %}
{% endblock extra_header %}

{% block content %}
  {% show_tigerleaflet_county 'map' "/tigerleaflet/" state county %}
{% endblock %}

geodjango_tigerleaflet_example/templates/pages/home.html
{% extends "app_base.html" %}

geodjango_tigerleaflet_example/templates/pages/state.html
{% extends "app_base.html" %}

{% load tigerleaflet_tags %}

{% block title %}{{ title }}{% endblock title %}

{% block extra_header %}
  {% init_tigerleaflet_map %}
{% endblock extra_header %}

{% block content %}
  {% show_tigerleaflet_state 'map' "/tigerleaflet/" state %}
{% endblock %}

tigerleaflet/templates/countryview_default.html
{% load tigerleaflet_tags %}

<html>
  <head>
    <title>{{ title }}</title>
    {% init_tigerleaflet_map %}
  </head>
  <body>
    {% show_tigerleaflet_country 'map' "/tigerleaflet/" 37.22 -90.41 3 %}
  </body>
</html>

tigerleaflet/templates/countyview_default.html
{% load tigerleaflet_tags %}

<html>
  <head>
    <title>{{ title }}</title>
    {% init_tigerleaflet_map %}
  </head>
  <body>
  {% show_tigerleaflet_county 'map' "/tigerleaflet/" state county %}
  </body>
</html>

tigerleaflet/templates/stateview_default.html
{% load tigerleaflet_tags %}

<html>
  <head>
    <title>{{ title }}</title>
    {% init_tigerleaflet_map %}
  </head>
  <body>
  {% show_tigerleaflet_state 'map' "/tigerleaflet/" state %}
  </body>
</html>

tigerleaflet/templates/tigerleaflet_country.html
 <div id={{ map_name }} class="leaflet-container-default"></div>
 <script>
  var {{ map_name }} = tigerleafletMap('{{ map_name }}', [{{ latitude }}, {{ longitude }}], {{ zoom_level }});

  var map_data = {
    prefix:   {{ prefix }},
    url:      "{% url 'tigerleaflet:country_data' %}",
    map:      {{ map_name }},
    function: goToState,
    data:     {
      csrfmiddlewaretoken : '{{ csrf_token }}',
      state               : "{{ state }}",
    },
    zoom: false,
  }
  getGeojson(map_data);

</script>

tigerleaflet/templates/tigerleaflet_county.html
 <div id={{ map_name }} class="leaflet-container-default"></div>
 <script>
  var {{ map_name }} = tigerleafletMap('{{ map_name }}');

  var map_data = {
    prefix:   {{ prefix }},
    url:      "{% url 'tigerleaflet:county_data' %}",
    map:      {{ map_name }},
    data:     {
      csrfmiddlewaretoken : '{{ csrf_token }}',
      state               : "{{ state }}",
      county              : "{{ county }}",
    },
    zoom:     true,
    function: null,
  }

  getGeojson(map_data);

</script>

tigerleaflet/templates/tigerleaflet_init.html
{% load leaflet_tags %}
{% load geojson_tags %}

{% leaflet_css %}
{% leaflet_js %}

{% load static from staticfiles %}
<link rel="stylesheet" href="{% static 'css/tigerleaflet.css' %}">
<script src='{% static "js/jquery.min.js" %}'></script>
<script src='{% static "js/tigerleaflet.js" %}'></script>

tigerleaflet/templates/tigerleaflet_state.html
 <div id={{ map_name }} class="leaflet-container-default"></div>
 <script>
  var {{ map_name }} = tigerleafletMap('{{ map_name }}');

  var map_data = {
    prefix:   {{ prefix }},
    url:      "{% url 'tigerleaflet:state_data' %}",
    map:      {{ map_name }},
    data:     {
      csrfmiddlewaretoken : '{{ csrf_token }}',
      state               : "{{ state }}",
    },
    zoom:     true,
    function: goToCounty,
  }

  getGeojson(map_data);

</script>